import type { Metadata } from "next";
import {Averia_Serif_Libre } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const averiaSerifLibre = Averia_Serif_Libre({
  weight: "400",
  variable: "--font-averia-serif-libre",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${averiaSerifLibre.variable}`}>
      <body className={`antialiased`}>
        {/* <Header /> */}
        <main className="h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
